### ISSUE TITLE
Crash When Loading up the world

### ISSUE THREAD

**Issue by SJ1133** [Raizunne/Redstonic#4] opened 2015-03-03 08:15 UTC
This is Crash i get ever 1/3 Times i load the game. http://pastebin.com/E4EAmGP4

**Comment by bochen415** [comment] 2015-03-28 02:19
I had intermittent isp problems and same thing occurs.
http://paste.ubuntu.com/10692795/

**Comment by Raizunne** [comment] 2015-03-29 02:38
It looks like the problem is when players dont have internet access. I'll fix this in the next version. Thanks for the input!

**Comment by Raizunne** [comment] 2015-03-29 03:00
Issue fixed as of version 1.2.1, please follow up if problem persists.

**Closed by Raizunne** 2015-03-29 03:00 UTC
